<!-- Generated by pkgdown: do not edit by hand -->
<!DOCTYPE html>
<html lang="en">
  <head>
  <meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title>Mushrooms — agaricus • extracat</title>

<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
<!-- Bootstrap -->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script>

<!-- Font Awesome icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous" />

<!-- clipboard.js -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script>

<!-- sticky kit -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script>

<!-- pkgdown -->
<link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script>



<meta property="og:title" content="Mushrooms — agaricus" />

<meta property="og:description" content="Characteristics of more than 8000 mushrooms." />
<meta name="twitter:card" content="summary" />



<!-- mathjax -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script>

<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->


  </head>

  <body>
    <div class="container template-reference-topic">
      <header>
      <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">extracat</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.7.6</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
      
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

      
      </header>

<div class="row">
  <div class="col-md-9 contents">
    <div class="page-header">
    <h1>Mushrooms</h1>
    
    <div class="hidden name"><code>agaricus.rd</code></div>
    </div>

    <div class="ref-description">
    
    <p>Characteristics of more than 8000 mushrooms.</p>
    
    </div>

    <pre class="usage"><span class='fu'><a href='https://www.rdocumentation.org/packages/utils/topics/data'>data</a></span>(<span class='st'>"agaricus"</span>)</pre>
        
    <h2 class="hasAnchor" id="format"><a class="anchor" href="#format"></a>Format</h2>

    <p>A data frame with 8124 observations on the following 23 variables.</p><dl class='dl-horizontal'>
    <dt><code>classes</code></dt><dd><p>a factor with levels <code>edible</code> <code>poisonous</code></p></dd>
    <dt><code>cap_shape</code></dt><dd><p>a factor with levels <code>bell</code> <code>conical</code> <code>convex</code> <code>flat</code> <code>knobbed</code> <code>sunken</code></p></dd>
    <dt><code>cap_surface</code></dt><dd><p>a factor with levels <code>fibrous</code> <code>grooves</code> <code>scaly</code> <code>smooth</code></p></dd>
    <dt><code>cap_color</code></dt><dd><p>a factor with levels <code>brown</code> <code>buff</code> <code>cinnamon</code> <code>gray</code> <code>green</code> <code>pink</code> <code>purple</code> <code>red</code> <code>white</code> <code>yellow</code></p></dd>
    <dt><code>bruises</code></dt><dd><p>a factor with levels <code>bruises</code> <code>no</code></p></dd>
    <dt><code>odor</code></dt><dd><p>a factor with levels <code>almond</code> <code>anise</code> <code>creosote</code> <code>fishy</code> <code>foul</code> <code>musty</code> <code>none</code> <code>pungent</code> <code>spicy</code></p></dd>
    <dt><code>gill_attachment</code></dt><dd><p>a factor with levels <code>attached</code> <code>free</code></p></dd>
    <dt><code>gill_spacing</code></dt><dd><p>a factor with levels <code>close</code> <code>crowded</code></p></dd>
    <dt><code>gill_size</code></dt><dd><p>a factor with levels <code>broad</code> <code>narrow</code></p></dd>
    <dt><code>gill_color</code></dt><dd><p>a factor with levels <code>black</code> <code>brown</code> <code>buff</code> <code>chocolate</code> <code>gray</code> <code>green</code> <code>orange</code> <code>pink</code> <code>purple</code> <code>red</code> <code>white</code> <code>yellow</code></p></dd>
    <dt><code>stalk_shape</code></dt><dd><p>a factor with levels <code>enlarging</code> <code>tapering</code></p></dd>
    <dt><code>stalk_root</code></dt><dd><p>a factor with levels <code>bulbous</code> <code>club</code> <code>equal</code> <code>rooted</code></p></dd>
    <dt><code>stalk_surface_above_ring</code></dt><dd><p>a factor with levels <code>fibrous</code> <code>scaly</code> <code>silky</code> <code>smooth</code></p></dd>
    <dt><code>stalk_surface_below_ring</code></dt><dd><p>a factor with levels <code>fibrous</code> <code>scaly</code> <code>silky</code> <code>smooth</code></p></dd>
    <dt><code>stalk_color_above_ring</code></dt><dd><p>a factor with levels <code>brown</code> <code>buff</code> <code>cinnamon</code> <code>gray</code> <code>orange</code> <code>pink</code> <code>red</code> <code>white</code> <code>yellow</code></p></dd>
    <dt><code>stalk_color_below_ring</code></dt><dd><p>a factor with levels <code>brown</code> <code>buff</code> <code>cinnamon</code> <code>gray</code> <code>orange</code> <code>pink</code> <code>red</code> <code>white</code> <code>yellow</code></p></dd>
    <dt><code>veil_type</code></dt><dd><p>a factor with levels <code>partial</code></p></dd>
    <dt><code>veil_color</code></dt><dd><p>a factor with levels <code>brown</code> <code>orange</code> <code>white</code> <code>yellow</code></p></dd>
    <dt><code>ring_number</code></dt><dd><p>a factor with levels <code>none</code> <code>one</code> <code>two</code></p></dd>
    <dt><code>ring_type</code></dt><dd><p>a factor with levels <code>evanescent</code> <code>flaring</code> <code>large</code> <code>none</code> <code>pendant</code></p></dd>
    <dt><code>spore_print_color</code></dt><dd><p>a factor with levels <code>black</code> <code>brown</code> <code>buff</code> <code>chocolate</code> <code>green</code> <code>orange</code> <code>purple</code> <code>white</code> <code>yellow</code></p></dd>
    <dt><code>population</code></dt><dd><p>a factor with levels <code>abundant</code> <code>clustered</code> <code>numerous</code> <code>scattered</code> <code>several</code> <code>solitary</code></p></dd>
    <dt><code>habitat</code></dt><dd><p>a factor with levels <code>grasses</code> <code>leaves</code> <code>meadows</code> <code>paths</code> <code>urban</code> <code>waste</code> <code>woods</code></p></dd>
  </dl>
    
    <h2 class="hasAnchor" id="source"><a class="anchor" href="#source"></a>Source</h2>

    <p>UCL Machine Learning Repository</p>
    

    <h2 class="hasAnchor" id="examples"><a class="anchor" href="#examples"></a>Examples</h2>
    <pre class="examples"><div class='input'><span class='fu'><a href='https://www.rdocumentation.org/packages/utils/topics/data'>data</a></span>(<span class='no'>agaricus</span>)
<span class='co'>## maybe str(agaricus) ; plot(agaricus) ...</span></div></pre>
  </div>
  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      
      <li><a href="#format">Format</a></li>

      <li><a href="#source">Source</a></li>
      
      <li><a href="#examples">Examples</a></li>
    </ul>

  </div>
</div>

      <footer>
      <div class="copyright">
  <p>Developed by Alexander Pilhoefer.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
   </div>

  

  </body>
</html>

